# Usar una imagen base de Node.js
FROM node:14

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar los archivos package.json y package-lock.json al directorio de trabajo
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de la aplicación al directorio de trabajo
COPY . .

# Construir la aplicación
RUN npm run build

# Exponer el puerto en el que la aplicación NestJS escuchará
EXPOSE 3002

# Comando para correr la aplicación
CMD ["npm", "run", "start:prod"]
